export LD_LIBRARY_PATH=/scratch/bdes/haorany7/anaconda3/envs/eureka/lib:$LD_LIBRARY_PATH
CUDA_VISIBLE_DEVICES=0 python train.py \
    task=ShadowHandRope \
    checkpoint='/home/jensenyuan/Projects/Eureka-Research/eureka/checkpoints/iter7_response0_ShadowHandRopeGPT_ep_3000.pth' \
    headless=False \
    force_render=True \
    graphics_device_id=0 \
    num_envs=1 \
    test=True \
    rl_device=cuda:0 \
    sim_device=cuda:0 \
    +weights_only=True